version: '3.1'

services:
  fastapi:
    build: .
    volumes:
      - ./fastapi:/app
    ports:
      - 8000:8000
    restart: always
    tty: true
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    container_name: postgres-db
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

# 名前付きボリュームの定義を追加
volumes:
  db-data: